<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.9.4 setup script
 * Date: Wed, 12 Feb 2020 11:23:44 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: MySQL Main [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'MySQL Main';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'http';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'root';
$cfg['Servers'][$i]['auth_http_realm'] = '';

/* End of servers configuration */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>